spring.datasource.url=jdbc:${postgresql://bus_attendance_db_fa61_user:TVNNiAkNvdrDvnALvC63rcnZshSc5m5i@dpg-d6j6pflm5p6s73dhob00-a/bus_attendance_db_fa61}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}