# PostgreSQL DB configuration
spring.datasource.url=jdbc:postgresql://dpg-d6j6pflm5p6s73dhob00-a.singapore-postgres.render.com:5432/bus_attendance_db_fa61
spring.datasource.username=bus_attendance_db_fa61_user
spring.datasource.password=TVNNiAkNvdrDvnALvC63rcnZshSc5m5i
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server configuration for public access
server.address=0.0.0.0
server.port=${PORT:8080}